apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: 0217f8f9ad36db5a9d7e5e3318d5d46207d85a27
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 4000
          targetPort: 4000
          protocol: TCP
      healthChecks: []
      name: test-demo-kube-main
      imagePullPolicy: Always
      imageRegistry: docker.io/nj93/test-demo-kube
      imagePullSecretName: imagepull-docker
      credentialId: credential_47194304-4a17-4f70-95b4-6ecc595cfb7b
      commitDetails:
        commitHash: 0217f8f9ad36db5a9d7e5e3318d5d46207d85a27
        commitAvatar: https://github.com/skyu-v2-dev[bot].png
        commitTime: '2024-05-16T16:15:44Z'
        commitMessage: deleted
        commitUser: skyu-v2-dev[bot]
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: test-demo-kube
    version: v1.0.0
    applicationId: app_ba6c7667-baac-4b90-bce2-953b4154a384
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    environmentId: env_12199eed-1603-479a-9d76-0c14583d9883
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: test-demo-kube
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-proj-1-dev
