apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: fd-main
      imagePullPolicy: Always
      imageRegistry: dfdf/fd
      credentialId: credential_ef5d35a8-00e1-44a6-9abc-b921b043a1e2
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: fd
    version: v1.0.0
    applicationId: app_25576efc-33ae-4d4e-96ca-c38a85d24011
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    environmentId: env_b8a4413c-521f-4686-8993-4a7c64a62735
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: fd
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-proj-1-staging
