apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cs
  namespace: scs
spec:
  chart:
    spec:
      chart: komiser
      reconcileStrategy: ChartVersion
      version: 3.1.10
      sourceRef:
        kind: HelmRepository
        name: komiser-eks
  interval: 5m0s
  releaseName: cs
  uninstall:
    keepHistory: false
  valuesFrom:
  - kind: ConfigMap
    name: komiser-configmap
    valuesKey: aws.serviceaccountarn
    targetPath: aws.serviceaccountarn
  - kind: ConfigMap
    name: komiser-configmap
    valuesKey: aws.arn
    targetPath: aws.arn
  postRenderers:
  - {}
