apiVersion: v1
kind: Namespace
metadata:
  name: demo-4-staging
  labels:
    environment-id: env_67aede82-bb64-4834-a32a-6f7cdc7065fc
    project-id: project_2f6b8d97-8bc6-4d03-bcca-d2147f1b5422
    project-name: demo-4
    environment-name: staging
    organization-id: org_fc18b32c-00a4-49d7-94ab-ee96b2c9569d
