apiVersion: v1
kind: Namespace
metadata:
  name: test-staging
  labels:
    environment-id: env_8de8739b-8161-4e0a-a985-f4f5d5ac3599
    project-id: project_d0a880a8-6a48-4dde-9ec0-53c53f464735
    project-name: test
    environment-name: staging
    organization-id: org_902bd82c-8fac-482d-b4cc-56d63ae183ba
