apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-demo-kube-v1-0-0
  labels:
    app: test-demo-kube-v1-0-0
    applicationId: app_ba6c7667-baac-4b90-bce2-953b4154a384
    version: v1.0.0
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: test-demo-kube-v1-0-0
  template:
    metadata:
      labels:
        app: test-demo-kube-v1-0-0
        applicationId: app_ba6c7667-baac-4b90-bce2-953b4154a384
        version: v1.0.0
        organizationId: org_83167af8-ae98-451b-972e-dca861896824
        projectId: project_ef675f23-db14-4843-93c7-fc931247adba
