apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: p-v1-0-0
  labels:
    app: p-v1-0-0
    applicationId: app_567603b4-7d37-4411-b038-0c32b09836d5
    version: v1.0.0
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: p-v1-0-0
