apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: nginx-v1-0-0
  labels:
    app: nginx-v1-0-0
    applicationId: app_8f770733-ef3d-4d2b-a4cf-f61221b8962c
    version: v1.0.0
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-v1-0-0
