apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: iwiick-do-not-touch-v1-0-0
  labels:
    app: iwiick-do-not-touch-v1-0-0
    applicationId: app_51e2d38a-7bde-40b8-b6a5-e65f11b57b97
    version: v1.0.0
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iwiick-do-not-touch-v1-0-0
