apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: iwiick-error-test-v1-0-0
  labels:
    app: iwiick-error-test-v1-0-0
    applicationId: app_e4ebcfae-3c40-4b33-8f4e-186ad00280d9
    version: v1.0.0
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iwiick-error-test-v1-0-0
