apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: iwiick-error-test-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/iwiick-error-test
      credentialId: credential_6df4f3e2-3a1f-432b-ad29-93e6ea6051fc
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: iwiick-error-test
    version: v1.0.0
    applicationId: app_e4ebcfae-3c40-4b33-8f4e-186ad00280d9
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    environmentId: env_12199eed-1603-479a-9d76-0c14583d9883
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: iwiick-error-test
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-proj-1-dev
