apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: a1f5568278c8bd0844bcd4c32878869596312c4f
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: ridmiiiiiiiiiiiiiiii-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/ridmiiiiiiiiiiiiiiii
      credentialId: credential_6df4f3e2-3a1f-432b-ad29-93e6ea6051fc
      commitDetails:
        commitHash: a1f5568278c8bd0844bcd4c32878869596312c4f
        commitAvatar: https://github.com/skyu-v2-dev[bot].png
        commitTime: '2024-03-19T02:43:04Z'
        commitMessage: Skyu container Template Workflows Created
        commitUser: skyu-v2-dev[bot]
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: ridmiiiiiiiiiiiiiiii
    version: v1.0.0
    applicationId: app_62520c7f-ca4b-4b20-95f3-1754b22e9f8a
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    environmentId: env_12199eed-1603-479a-9d76-0c14583d9883
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: ridmiiiiiiiiiiiiiiii
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-proj-1-dev
