apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 4000
          targetPort: 4000
          protocol: TCP
          apiSpec:
            gitPath: docs/swagger.json
      healthChecks: []
      name: swagger-problem-main
      imagePullPolicy: Always
      imageRegistry: docker.io/nj93/swagger-problem
      imagePullSecretName: imagepull-docker
      credentialId: credential_47194304-4a17-4f70-95b4-6ecc595cfb7b
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: swagger-problem
    version: v1.0.0
    applicationId: app_acfd460b-bc14-4f10-bafc-256657aed02c
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    environmentId: env_b8a4413c-521f-4686-8993-4a7c64a62735
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: swagger-problem
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-proj-1-staging
