apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: test-service-2-v1-0-0
  labels:
    app: test-service-2-v1-0-0
    applicationId: app_e4c5f1ef-82de-4f21-8281-7be71630577f
    version: v1.0.0
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-service-2-v1-0-0
