apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: test-service-2-v1-0-0
    applicationId: app_e4c5f1ef-82de-4f21-8281-7be71630577f
    version: v1.0.0
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
  name: test-service-2-v1-0-0
spec:
  selector:
    app: test-service-2-v1-0-0
