apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: delete-service-v1-0-0
  labels:
    app: delete-service-v1-0-0
    applicationId: app_acb65c4c-af85-460c-a8f2-e76972f40e3b
    version: v1.0.0
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_ef675f23-db14-4843-93c7-fc931247adba
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: delete-service-v1-0-0
